# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c82dabe588ec82b7ef7f9126e2a80af417fc638f9eaf1d681f394e8c7d1b24e59300074c37132ae922882886476e80c3411463e889d701501c7fcbf06c5ed2e

test:
  secret_key_base: 7ff8c87fd08c5258fddd02845baa0230646643dccacc913046a16326289f099aac92c6d948864bf477127c489f8ef9c7d979cc3e8c784a622b07cfa7ce90d56a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
